New Map: Onion Ocean
FortuneStreetModding/fortunestreetmodding.github.io pull request #224
Opened 2024-07-14 23:01 UTC by alexoutsold

2024-07-18 03:23 UTC, Sophilautia commented
Hi @alexoutsold

Please complete the board submission checklist here: https://forms.gle/E1fwdGCHuAxhDLPr9

You will need to upload the background and music to google drive in a zip, the background files (except the map icon) will need to be removed from your Pull Request.

2024-07-18 03:26 UTC, Sophilautia commented
Also noticed these errors in the validation:

```
Additional properties are not allowed ('capitalShopNames' was unexpected)
YAML files shall no longer contain the line '---' or '...'
```

2024-08-24 15:52 UTC, Ennesan commented
There are no authors listed in the Onion.YAML file.

2024-09-03 08:35 UTC, Sophilautia commented
Right, @alexoutsold this needs a couple of changes.

1. Yaml needs author section
2. Yaml needs changelog section
3. Max Dice Roll is set to 7, but Venture Card 87 is enabled. Venture Card 87 makes the player roll either a 7 or an 8, which can work, but can also cause issues since this value being higher than the Max Dice Roll makes it very hard to test pathing for. Please either change the max dice roll to 8 or change Venture Card 87 to something else.

2024-10-20 05:47 UTC, Ennesan requested changes
You are missing one activated Venture Card due to having deactivated Venture Card 87. Please add one more venture card to be activated.

2024-10-20 05:50 UTC, Ennesan commented
![スクリーンショット 2024-10-20 144947](https://github.com/user-attachments/assets/9d5f683f-04aa-40a7-9590-4254a6c61ee6)
The points noted above correspond to the red line in this image.

2025-01-05 01:20 UTC, merged